# Generated by Django 5.0.4 on 2024-04-13 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_num',
            new_name='phone_number',
        ),
    ]
